[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

before-all = [
    "mkdir -p bin obj aindex/core aindex/bin",
]

before-build = [
    "pip install pybind11 numpy",
    "echo '=== Building wheel for {arch} ==='",
    "echo 'Current directory: ' && pwd",
    "echo 'ARCHFLAGS: ${ARCHFLAGS:-not set}'",
    "echo 'Machine arch: ' && uname -m",
    "make clean || true",
    "make all",
    # Проверяем архитектуру собранного файла
    "echo '=== Checking built extension architecture ==='",
    "file aindex/core/aindex_cpp*.so || echo 'Extension not found'",
    "lipo -info aindex/core/aindex_cpp*.so || echo 'Cannot check architecture'",
]

repair-wheel-command = "cp {wheel} {dest_dir}"

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "11.0"
MAKEFLAGS = "-j1"
# cibuildwheel автоматически подставит правильную архитектуру
ARCHFLAGS = "-arch {arch}"