[build-system]
requires = ["setuptools>=61.0,<70.0", "wheel>=0.40.0,<0.44.0", "pybind11>=2.6.0", "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "aindex2"
version = "1.3.10"
description = "Perfect hash based index for genome data."
authors = [{name = "Aleksey Komissarov", email = "ad3002@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
]
dependencies = [
    "numpy>=1.20.0",
    "intervaltree==3.1.0",
    "editdistance==0.8.1",
]

[project.urls]
Homepage = "https://github.com/ad3002/aindex"
"Bug Tracker" = "https://github.com/ad3002/aindex/issues"
"Source Code" = "https://github.com/ad3002/aindex"

[project.scripts]
aindex2 = "aindex.cli:main"

[tool.setuptools]
packages = ["aindex", "aindex.core"]

[tool.setuptools.package-data]
aindex = ["bin/*"]
"aindex.core" = ["*.so", "aindex_cpp*.so", "*.pyd"]

[tool.cibuildwheel]
# Build for Python 3.8+ on all platforms
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
skip = "*-musllinux*"  # Skip musl Linux for simplicity
test-command = "python -c 'import aindex; print(\"Import successful\")'"

# Linux-specific configuration
[tool.cibuildwheel.linux]
archs = ["x86_64"]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
before-all = """
    yum install -y cmake make gcc-c++ git || apt-get update && apt-get install -y cmake make build-essential git
    mkdir -p external
    cd external
    git clone https://github.com/ad3002/emphf.git
    cd emphf
    patch -p1 < ../../patches/emphf_cmake_version.patch || true
    cmake .
    make
    cd ../../
    """

# macOS-specific configuration
[tool.cibuildwheel.macos]
archs = ["x86_64"]
before-all = """
    mkdir -p external
    cd external
    git clone https://github.com/ad3002/emphf.git
    cd emphf
    patch -p1 < ../../patches/emphf_cmake_version.patch || true
    cmake .
    make
    cd ../../
    """