[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = """
  uname -a
  mkdir -p external
  cd external
  git clone https://github.com/ad3002/emphf.git
  cd emphf
  cmake .
  make
  cd ../../
  """
environment = { CIBW_BUILD = "cp3?-*-manylinux*, cp3?-*-win_amd64, cp3?-*-macosx_x86_64" }