{% set version = "1.0.0" %}

package:
  name: aindex
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools >=40.8
    - cmake
    - gxx_linux-64
  run:
    - python

about:
  home: https://github.com/ad3002/aindex
  license: MIT
  summary: Perfect hash based index for genome data.
