name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # Clone and build external dependencies
      - name: Build external dependencies
        run: |
          mkdir -p external
          cd external
          git clone https://github.com/ad3002/emphf.git
          cd emphf
          cmake .
          make

      - name: Build wheels
        run: pipx run cibuildwheel==2.19.2

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl