name: Build and Publish

# Simplified CI/CD after emphf integration - no external dependencies required
# Builds wheels for Linux and macOS using local emphf sources

on:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Возвращаем macOS после упрощения зависимостей
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          # No additional dependencies needed - Xcode tools provide make and g++
          echo "macOS build tools ready"

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake git
          # Ensure Visual Studio tools are available
          echo "CMAKE_GENERATOR=Visual Studio 17 2022" >> $env:GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cibuildwheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          # Build for all supported Python versions
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-musllinux*"  # Пропускаем только musl Linux
          
          # Platform-specific before_all commands
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y make gcc-c++ || apt-get update && apt-get install -y make build-essential
            echo "Building with local emphf sources..."
            echo "=== Debug Makefile Variables ==="
            make debug-vars
            echo "=== Building all binaries using local sources ==="
            make clean
            make all
            echo "Available binaries:"
            ls -la bin/
            echo "✓ Local build completed successfully"
          
          CIBW_BEFORE_ALL_MACOS: |
            echo "Building with local emphf sources on macOS..."
            echo "=== Debug Makefile Variables ==="
            make debug-vars
            echo "=== Building all binaries using local sources ==="
            make clean
            make all
            echo "Available binaries:"
            ls -la bin/
            echo "✓ Local build completed successfully"
          
          CIBW_BEFORE_ALL_WINDOWS: |
            mkdir external
            cd external
            git clone https://github.com/ad3002/emphf.git
            cd emphf
            cmake -G "Visual Studio 17 2022" .
            cmake --build . --config Release
            cd ..\\..
          
          # Platform-specific before_build commands
          CIBW_BEFORE_BUILD: |
            pip install pybind11 numpy
            python -c "import sys; print(f'Building for Python {sys.version}')"
            python -c "import pybind11; print(f'pybind11 include: {pybind11.get_include()}')"
          
          CIBW_BEFORE_BUILD_LINUX: |
            pip install pybind11 numpy
            python -c "import sys; print(f'Python: {sys.executable}')"
            python -c "import pybind11; print(f'pybind11: {pybind11.get_include()}')"
            # Set environment variable for cibuildwheel detection
            export CIBUILDWHEEL=1
            # Only build pybind11 extension, binaries are already built in BEFORE_ALL
            make pybind11
          
          CIBW_BEFORE_BUILD_MACOS: |
            pip install pybind11 numpy
            python -c "import sys; print(f'Python: {sys.executable}')"
            python -c "import pybind11; print(f'pybind11: {pybind11.get_include()}')"
            # Set environment variable for cibuildwheel detection
            export CIBUILDWHEEL=1
            # Only build pybind11 extension, binaries are already built in BEFORE_ALL
            make pybind11
          
          CIBW_BEFORE_BUILD_WINDOWS: |
            pip install cmake pybind11 numpy
            python setup.py build_ext --inplace
          
          # Repair wheels (Linux only) - simplified macOS repair
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
            auditwheel repair -w {dest_dir} {wheel}
          
          # Use delocate-wheel without arch requirements for macOS
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            delocate-wheel -w {dest_dir} {wheel} || cp {wheel} {dest_dir}
          
          # Test wheels - simplified for cross-platform compatibility
          CIBW_TEST_COMMAND_LINUX: |
            python -c "import aindex; print('✓ Import successful')"
          
          CIBW_TEST_COMMAND_MACOS: |
            python -c "import aindex; print('✓ Import successful')"
          
          CIBW_TEST_COMMAND_WINDOWS: |
            python -c "import aindex; print('✓ Import successful')"
          
          # Environment variables
          CIBW_ENVIRONMENT_LINUX: MAKEFLAGS="-j$(nproc)"
          CIBW_ENVIRONMENT_MACOS: MAKEFLAGS="-j$(sysctl -n hw.ncpu)"
          
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
          
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential

      - name: Build sdist
        run: |
          pip install setuptools wheel pybind11 numpy
          python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: List artifacts
        run: ls -la dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}